---
- hosts: gitlab_server
  # Run commands as root
  become: true
  # Roles to be executed on these hosts
  roles:
  - role: gitlab/install
    tags: install

  - role: gitlab/healthchecks
    tags: check

ansible-playbook /vagrant/playbooks/run.yml --tags self_managed -i /tmp/vagrant-ansible/inventory/vagrant_ansible_local_inventory -e "check_type=all"
